# Generated by Django 4.1.7 on 2023-03-23 10:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('user_name', models.CharField(max_length=30, verbose_name='Foydalanuvchining ismi')),
                ('user_lastname', models.CharField(max_length=30, verbose_name='Foydalanuvchining familiyasi')),
                ('user_age', models.IntegerField(verbose_name='Foydalanuvchining yoshi')),
                ('user_workplace', models.CharField(max_length=30, verbose_name='Foydalanuvchining ishjoyi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
